/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/model-endpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Endpoint */
        get: operations["get_model_endpoint_api_settings_model_endpoint_get"];
        put?: never;
        /** Save Model Endpoint */
        post: operations["save_model_endpoint_api_settings_model_endpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/model-endpoint/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model Endpoint */
        post: operations["test_model_endpoint_api_settings_model_endpoint_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Settings */
        get: operations["get_app_settings_api_settings_app_get"];
        put?: never;
        /** Save App Settings */
        post: operations["save_app_settings_api_settings_app_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_api_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/dashboard-from-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dashboard From Csv */
        post: operations["dashboard_from_csv_api_artifacts_dashboard_from_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Pdf */
        post: operations["export_pdf_api_artifacts__artifact_id__export_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}/export/pdf/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Pdf */
        get: operations["download_pdf_api_artifacts__artifact_id__export_pdf_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Backward-compatible chat endpoint — checks intent first.
         *
         *     For artifact intents (dashboard, report, chart, table, summary) with
         *     a CSV file, generates the artifact and returns immediately.
         *
         *     For normal chat, delegates to the agent runtime.
         */
        post: operations["send_message_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Backward-compatible chat endpoint — checks intent first.
         *
         *     For artifact intents (dashboard, report, chart, table, summary) with
         *     a CSV file, generates the artifact and returns immediately.
         *
         *     For normal chat, delegates to the agent runtime.
         */
        post: operations["send_message_api_chat_artifact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hardware */
        get: operations["get_hardware_api_system_hardware_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/hardware/managed-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hardware Managed Plan
         * @description Detect hardware and return a managed plan recommendation.
         */
        get: operations["get_hardware_managed_plan_api_system_hardware_managed_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Models assigned to this machine's hardware tier (from the managed plan).
         *
         *     Returned in CatalogModel shape for the setup download step. These are the
         *     real tier-assigned models — there is no fictional/static catalog.
         */
        get: operations["get_catalog_api_models_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Status
         * @description Live status of the models assigned to this machine's hardware tier.
         *
         *     The model list comes from the resolved managed plan (hardware_catalog.json),
         *     NOT from stored endpoint config. For each role we report a tri-state:
         *       - missing:   not installed on this machine (download required)  → red
         *       - installed: on disk but not currently loaded into memory       → yellow
         *       - loaded:    resident in memory and serving (verified working)  → green
         *
         *     The orchestrator role is the model the user actually chats to, so
         *     ``chat_ready`` reflects that role being loaded and the runtime reachable.
         */
        get: operations["get_model_status_api_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_api_folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_api_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Folder */
        delete: operations["delete_folder_api_folders__folder_id__delete"];
        options?: never;
        head?: never;
        /** Rename Folder */
        patch: operations["rename_folder_api_folders__folder_id__patch"];
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_api_chats_get"];
        put?: never;
        /** Create Chat */
        post: operations["create_chat_api_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_api_chats__chat_id__get"];
        put?: never;
        post?: never;
        /** Delete Chat */
        delete: operations["delete_chat_api_chats__chat_id__delete"];
        options?: never;
        head?: never;
        /** Update Chat */
        patch: operations["update_chat_api_chats__chat_id__patch"];
        trace?: never;
    };
    "/api/setup/managed-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Managed Plan
         * @description Detect hardware and resolve a managed plan.
         */
        get: operations["get_managed_plan_api_setup_managed_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/managed-plan/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Managed Plan
         * @description Persist the resolved managed plan and create a provisioning job record.
         */
        post: operations["confirm_managed_plan_api_setup_managed_plan_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/provisioning/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provisioning Job
         * @description Return provisioning job snapshot including per-model item states.
         */
        get: operations["get_provisioning_job_api_setup_provisioning__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/provisioning/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provisioning Events
         * @description SSE stream of provisioning events for a job.
         */
        get: operations["get_provisioning_events_api_setup_provisioning__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/provisioning/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Provisioning
         * @description Reset failed items and restart background provisioning for this job.
         */
        post: operations["retry_provisioning_api_setup_provisioning__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["shutdown_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facts
         * @description List all active (non-deleted) memory facts.
         */
        get: operations["list_facts_api_memory_facts_get"];
        put?: never;
        /**
         * Create Fact
         * @description Create a user-initiated memory fact (user_locked=true by default).
         */
        post: operations["create_fact_api_memory_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Fact
         * @description Soft-delete a fact: set deleted_at, keep vector for tombstone.
         */
        delete: operations["delete_fact_api_memory_facts__fact_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Fact
         * @description Update a fact's text, recompute embedding, set user_locked=true.
         */
        patch: operations["update_fact_api_memory_facts__fact_id__patch"];
        trace?: never;
    };
    "/api/mcp/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tools
         * @description Return the list of allowed tool definitions from config.
         */
        get: operations["get_tools_api_mcp_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/tools/{tool_name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tool Status
         * @description Check if a specific tool is available.
         */
        get: operations["get_tool_status_api_mcp_tools__tool_name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-packs/installed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Installed Packs */
        get: operations["get_installed_packs_api_knowledge_packs_installed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-packs/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install Local Pack */
        post: operations["install_local_pack_api_knowledge_packs_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Uninstall Local Pack */
        delete: operations["uninstall_local_pack_api_knowledge_packs__pack_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSettingsDTO */
        AppSettingsDTO: {
            /**
             * Setup Complete
             * @default false
             */
            setup_complete: boolean;
            /**
             * Setup Mode
             * @default managed
             * @enum {string}
             */
            setup_mode: "managed" | "byo";
            /**
             * Theme
             * @default system
             * @enum {string}
             */
            theme: "light" | "dark" | "system";
            /**
             * Active Models
             * @default []
             */
            active_models: string[];
            /**
             * Managed Plan
             * @default {}
             */
            managed_plan: {
                [key: string]: unknown;
            };
            /**
             * Workers Enabled
             * @default true
             */
            workers_enabled: boolean;
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Artifact */
            artifact: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_file_api_files_upload_post */
        Body_upload_file_api_files_upload_post: {
            /** File */
            file: string;
        };
        /** CatalogModel */
        CatalogModel: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Size */
            size: string;
            /** Size Gb */
            size_gb: number;
            /**
             * Fit
             * @enum {string}
             */
            fit: "ok" | "warn" | "bad";
            /** Note */
            note: string;
        };
        /** ChatDTO */
        ChatDTO: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Folder Id */
            folder_id?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ChatDetailDTO */
        ChatDetailDTO: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Folder Id */
            folder_id?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["ChatMessageDTO"][];
        };
        /** ChatMessageDTO */
        ChatMessageDTO: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Artifacts
             * @default []
             */
            artifacts: string[];
            /**
             * Files
             * @default []
             */
            files: {
                [key: string]: unknown;
            }[];
            /** Created At */
            created_at: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Chat Id */
            chat_id?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * File Ids
             * @default []
             */
            file_ids: string[];
            /** Assistant Message Id */
            assistant_message_id?: string | null;
            /** Workers Enabled */
            workers_enabled?: boolean | null;
            /**
             * Web Search
             * @default false
             */
            web_search: boolean;
            /**
             * Thinking Enabled
             * @default false
             */
            thinking_enabled: boolean;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Chat Id */
            chat_id: string;
            message: components["schemas"]["ChatMessageDTO"];
            /**
             * Memory Events
             * @default []
             */
            memory_events: {
                [key: string]: unknown;
            }[];
        };
        /** CreateChatRequest */
        CreateChatRequest: {
            /**
             * Title
             * @default New chat
             */
            title: string;
            /** Folder Id */
            folder_id?: string | null;
        };
        /** CreateFolderRequest */
        CreateFolderRequest: {
            /**
             * Name
             * @default New folder
             */
            name: string;
        };
        /** DashboardFromCsvRequest */
        DashboardFromCsvRequest: {
            /** File Id */
            file_id: string;
            /** Instruction */
            instruction?: string | null;
        };
        /** ExportPdfResponse */
        ExportPdfResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Download Path */
            download_path: string;
            /** Filename */
            filename: string;
        };
        /** FileDTO */
        FileDTO: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type?: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Row Count */
            row_count?: number | null;
            /** Columns */
            columns?: string[] | null;
            /** Created At */
            created_at: string;
        };
        /** FolderDTO */
        FolderDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
        };
        /** GpuInfo */
        GpuInfo: {
            /** Name */
            name: string;
            /** Vram Gb */
            vram_gb?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareInfo */
        HardwareInfo: {
            /** Os */
            os: string;
            /** Cpu */
            cpu: string;
            /** Ram Gb */
            ram_gb?: number | null;
            /**
             * Gpu
             * @default []
             */
            gpu: components["schemas"]["GpuInfo"][];
            /** Vram Gb */
            vram_gb?: number | null;
            /**
             * Recommended Profile
             * @default external_endpoint
             * @enum {string}
             */
            recommended_profile: "local" | "external_endpoint";
        };
        /** ManagedPlanResponse */
        ManagedPlanResponse: {
            /**
             * Path
             * @enum {string}
             */
            path: "apple" | "gpu" | "cpu_only" | "reject";
            /** Plan Id */
            plan_id?: string | null;
            /** Plan Rank */
            plan_rank?: number | null;
            /** Ctx */
            ctx?: number | null;
            /**
             * Helper Count
             * @default 0
             */
            helper_count: number;
            /** Fingerprint Hash */
            fingerprint_hash: string;
            /**
             * Runtime Priority
             * @default []
             */
            runtime_priority: string[];
            /**
             * Runtime Forbidden
             * @default []
             */
            runtime_forbidden: string[];
            /**
             * Required Launch Flags
             * @default []
             */
            required_launch_flags: string[];
            /**
             * Recommended Setup Mode
             * @default managed
             * @enum {string}
             */
            recommended_setup_mode: "managed" | "byo";
            /**
             * Action
             * @default
             */
            action: string;
            /** Reason */
            reason?: string | null;
            /**
             * Detection Warnings
             * @default []
             */
            detection_warnings: string[];
            orchestrator?: components["schemas"]["ModelRef"] | null;
            summarizer?: components["schemas"]["ModelRef"] | null;
            utility?: components["schemas"]["ModelRef"] | null;
            /** Optional Orchestrator */
            optional_orchestrator?: {
                [key: string]: unknown;
            } | null;
            /**
             * Validation Stubbed
             * @default true
             */
            validation_stubbed: boolean;
        };
        /** MemoryFactCreateRequest */
        MemoryFactCreateRequest: {
            /** Fact Text */
            fact_text: string;
        };
        /** MemoryFactDTO */
        MemoryFactDTO: {
            /** Id */
            id: string;
            /** Fact Text */
            fact_text: string;
            /** Source Chat Id */
            source_chat_id?: string | null;
            /**
             * User Locked
             * @default false
             */
            user_locked: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** MemoryFactUpdateRequest */
        MemoryFactUpdateRequest: {
            /** Fact Text */
            fact_text: string;
        };
        /** ModelEndpointConfig */
        ModelEndpointConfig: {
            /**
             * Provider
             * @default openai_compatible
             * @constant
             */
            provider: "openai_compatible";
            /**
             * Base Url
             * @example http://localhost:11434/v1
             */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            models?: components["schemas"]["ModelRoles"];
        };
        /** ModelRef */
        ModelRef: {
            /** Model */
            model: string;
            /** Quant */
            quant: string;
            /**
             * Device
             * @default gpu
             */
            device: string;
            /** Ctx Min */
            ctx_min?: number | null;
            /** Ctx Max */
            ctx_max?: number | null;
        };
        /** ModelRoles */
        ModelRoles: {
            /**
             * Orchestrator
             * @default
             */
            orchestrator: string;
            /**
             * Summarizer
             * @default
             */
            summarizer: string;
            /**
             * Utility
             * @default
             */
            utility: string;
        };
        /** PackInstallRequest */
        PackInstallRequest: {
            /** Pack Path */
            pack_path: string;
        };
        /** PackRegistryResponse */
        PackRegistryResponse: {
            /** Pack Id */
            pack_id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Installed At */
            installed_at: string;
            /** Source Path */
            source_path: string;
            /** Pack Path */
            pack_path: string;
            /** Checksum Ok */
            checksum_ok: boolean;
            /** Status */
            status: string;
        };
        /** TestConnectionResult */
        TestConnectionResult: {
            /** Ok */
            ok: boolean;
            /**
             * Models
             * @default []
             */
            models: string[];
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** UpdateChatRequest */
        UpdateChatRequest: {
            /** Title */
            title?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /**
             * Unfile
             * @default false
             */
            unfile: boolean;
        };
        /** UpdateFolderRequest */
        UpdateFolderRequest: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_model_endpoint_api_settings_model_endpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEndpointConfig"];
                };
            };
        };
    };
    save_model_endpoint_api_settings_model_endpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelEndpointConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEndpointConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_endpoint_api_settings_model_endpoint_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelEndpointConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_settings_api_settings_app_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsDTO"];
                };
            };
        };
    };
    save_app_settings_api_settings_app_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_files_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_from_csv_api_artifacts_dashboard_from_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardFromCsvRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pdf_api_artifacts__artifact_id__export_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPdfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_pdf_api_artifacts__artifact_id__export_pdf_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_chat_artifact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hardware_api_system_hardware_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareInfo"];
                };
            };
        };
    };
    get_hardware_managed_plan_api_system_hardware_managed_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_catalog_api_models_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogModel"][];
                };
            };
        };
    };
    get_model_status_api_models_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_folders_api_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDTO"][];
                };
            };
        };
    };
    create_folder_api_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_folder_api_folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDTO"][];
                };
            };
        };
    };
    create_chat_api_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_api_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_api_chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_api_chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_managed_plan_api_setup_managed_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlanResponse"];
                };
            };
        };
    };
    confirm_managed_plan_api_setup_managed_plan_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_provisioning_job_api_setup_provisioning__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provisioning_events_api_setup_provisioning__job_id__events_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_provisioning_api_setup_provisioning__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_facts_api_memory_facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFactDTO"][];
                };
            };
        };
    };
    create_fact_api_memory_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryFactCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFactDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fact_api_memory_facts__fact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fact_api_memory_facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryFactUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFactDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tools_api_mcp_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_tool_status_api_mcp_tools__tool_name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_installed_packs_api_knowledge_packs_installed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRegistryResponse"][];
                };
            };
        };
    };
    install_local_pack_api_knowledge_packs_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackInstallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackRegistryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uninstall_local_pack_api_knowledge_packs__pack_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
