/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical artifact spec. Source of truth for both the TypeScript renderers (frontend) and the Pydantic models (backend). The LLM/agent only ever emits these specs; the app renders them deterministically.
 */
export type Artifact = DashboardArtifact | ReportArtifact | ChartArtifact | TableArtifact | DocumentArtifact;
export type Scalar = string | number;

export interface DashboardArtifact {
  id: string;
  artifact_type: "dashboard";
  title: string;
  summary?: string;
  created_at: string;
  source_file_id?: string;
  spec: DashboardSpec;
}
export interface DashboardSpec {
  cards: Card[];
  charts: Chart[];
  tables: Table[];
  insights: string[];
}
/**
 * A single headline metric / KPI card.
 */
export interface Card {
  label: string;
  value: Scalar;
  /**
   * e.g. '+11% vs Q1'
   */
  delta?: string;
  trend?: "up" | "down" | "flat";
  description?: string;
}
export interface Chart {
  type: "bar" | "line" | "area" | "pie";
  title: string;
  x: string[];
  series: Series[];
  stacked?: boolean;
  note?: string;
}
export interface Series {
  name: string;
  data: number[];
}
export interface Table {
  title: string;
  columns: string[];
  rows: Scalar[][];
}
export interface ReportArtifact {
  id: string;
  artifact_type: "report";
  title: string;
  summary?: string;
  created_at: string;
  source_file_id?: string;
  spec: ReportSpec;
}
export interface ReportSpec {
  prepared?: string;
  prepared_for?: string;
  prepared_by?: string;
  sections: ReportSection[];
}
export interface ReportSection {
  heading: string;
  paragraphs: string[];
  table?: Table;
}
export interface ChartArtifact {
  id: string;
  artifact_type: "chart";
  title: string;
  summary?: string;
  created_at: string;
  source_file_id?: string;
  spec: ChartSpec;
}
export interface ChartSpec {
  chart: Chart;
}
export interface TableArtifact {
  id: string;
  artifact_type: "table";
  title: string;
  summary?: string;
  created_at: string;
  source_file_id?: string;
  spec: TableSpec;
}
export interface TableSpec {
  table: Table;
}
export interface DocumentArtifact {
  id: string;
  artifact_type: "document";
  title: string;
  summary?: string;
  created_at: string;
  source_file_id?: string;
  spec: DocumentSpec;
}
export interface DocumentSpec {
  markdown: string;
}
